/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Matrix */

#ifndef _Included_Matrix
#define _Included_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Matrix
 * Method:    transpose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Matrix_transpose
  (JNIEnv *, jobject);

/*
 * Class:     Matrix
 * Method:    add
 * Signature: (LMatrix;)LMatrix;
 */
JNIEXPORT jobject JNICALL Java_Matrix_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Matrix
 * Method:    subtract
 * Signature: (LMatrix;)LMatrix;
 */
JNIEXPORT jobject JNICALL Java_Matrix_subtract
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
