#include <../Core/LinearAlgebra/matrix_2x2.hpp>
#include <../Core/LinearAlgebra/matrix_2x3.hpp>
#include <../Core/LinearAlgebra/matrix_2x4.hpp>
#include <../Core/LinearAlgebra/matrix_3x2.hpp>
#include <../Core/LinearAlgebra/matrix_3x3.hpp>
#include <../Core/LinearAlgebra/matrix_3x4.hpp>
#include <../Core/LinearAlgebra/matrix_4x2.hpp>
#include <../Core/LinearAlgebra/matrix_4x3.hpp>
#include <../Core/LinearAlgebra/matrix_4x4.hpp>
#include <../Core/LinearAlgebra/matrix_generic.hpp>